### Endpoint de teste
GET http://localhost:3003/ping

### Criar uma competição
POST http://localhost:3003/competition
Content-Type: application/json

{
    "title": "100m rasos classificatoria 1",
    "status": true
}

### Cadastrar resultados para uma competição
POST http://localhost:3003/competition/001
Content-Type: application/json

{
    "competition": "100m classificatoria 1", 
    "athlete": "Joao das Neves", 
    "value": "10.234", 
    "unit": "s"
}

### Finalizar uma competição
PUT http://localhost:3003/competition/001

### Retornar o ranking da competição
GET http://localhost:3003/competition/001
