### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
	"name": "Michael Scott",
	"email": "michael@dundermifflin.com",
	"password": "theboss"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
	"email": "michael@dundermifflin.com",
	"password": "theboss"
}

### 3) Get All
GET http://localhost:3003/users/all
Authorization: bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b

### 4) Delete By Id
GET  http://localhost:3003/users/f03017bb-2c08-4cdc-bb63-7fbd7cebe01f
Authorization: bb9b7ee8-ae4b-4bd1-9bd6-e7e21594399b
