### 1) Signup
POST http://localhost:3003/contributors
Content-Type: application/json

{
    "firstName": "Shikamaru",
    "lastName": "Nara",
    "participation": 4
}

### 2) Get users
GET http://localhost:3004/users
